### ISSUE TITLE
Issue with/incomplete description of covering things with miniaturization fluid

### ISSUE THREAD

**Issue by pdohogne** [CompactMods/CompactMachines#211]
In minecraft 1.10.2:

I found, in trying to automate creation of machine walls, that there's an additional requirement in the layout of the crafting recipes: there must be a floor around the entire structure.  That is, if there is not a floor one space out around the blocks to miniaturize, it will not work; the blocks must be placed as such (side view):
```
[I] = iron block
[F] = floor

   [I][I][I]
[F][F][F][F][F]
```

This structure, for example, will not work:
```
[I][I][I]
[F][F][F]
```

If the structure is instead built in midair or without the floor, it will not be recognized as correct and the fluid will eat the items thrown on it to try to finalize the crafting.  This issue may have something to do with how you're checking for fluid on the sides of the structure + minecraft flow mechanics.

If this is intentional, it should be noted in the in-game documentation somewhere.  If not, it should be fixed; this caused me over an hour of trying to debug my automation setup.  Additionally, if the layout is not correct, in my opinion the items thrown to finalize the crafting should not be consumed (an incorrect recipe for other types of crafting does not eat ingredients).  An error message would be helpful, but probably unnecessary.

**Comment by ouroborus** [comment]
This applies also to the miniaturization fluid source blocks. They have to be touching the structure to count. For example, the recipe for Tunnel indicates it takes ~4 buckets. However, there is no way to cover it and have the source blocks touching the structure with only 4 buckets. You need at least 5 in order to have all the source blocks touching while also covering the whole construction in fluid.

Personally, I'd say check that the structure has fluid, flowing or source, on all top and side surfaces. If this is true, the structure can be made successfully. (Ignore anything else that's adjacent. If there's a random block on the top or side, the earlier check will fail naturally. It doesn't matter if there are blocks adjacent to the bottoms.) Starting with the adjacent flowing blocks, trace all connected flowing blocks back to their sources, adjacent to the structure or not. These are all the source blocks that count towards the build. From here, it's business as usual. Remove all structure and source blocks. Generate the resulting compact machine block.

**Comment by davenonymous** [comment]
Miniaturization Crafting will work differently in CM3 (the 1.12 version).
How exactly I'm not sure yet - probably some sort of frame you'd have to build around it.
