### ISSUE TITLE
Mitigate room wall bypass

### ISSUE THREAD

**Issue by ouroborus** [CompactMods/CompactMachines#221]
Currently, other mods can allow players to exit the compact machine room volume, allowing access to the remainder of its pocket dimension. (I'm looking at you, EnderIO.) Any chance we could get something added to mitigate this sort of thing?

(RandomThings also has an extra-dimensional room available. They deny access to the rest of the dimension by teleporting players that are outside the room volume back inside unless they happen to be in creative mode.)

**Comment by davenonymous** [comment]
Yes, this feature will be back.
I forgot to re-add this functionality in CM3 when I removed it from CM2, because I had some changes regarding player miniaturization in mind. But since that's not an option anymore, I'll probably just re-add the same functionality that CM1 had: teleport you back into the room.

**Comment by Thunder-Nova** [comment]
I was thinking something along the line to use a GUI to decide on the cube player protection. If a player is blacklisted or not in the whitelist they get teleported out.

**Comment by Thunder-Nova** [comment]
That way can be made so that friends can get in. Plus open to the idea to "bridge" between cubes.
Such as a compact bridge or tube in between compact cubes placed outside. Making a less teleporting way to travel between them.

**Comment by ouroborus** [comment]
@Thunder-Nova Was there ever any protection in the old versions? I was under the impression that anybody with access to the block could get access to the "interior" if they had a miniaturizing device. This seems as it should be.

Maybe set it up so that rather than teleporting the player back into the cube volume, teleport them back to world proper as though they'd exited normally. Maybe with some damage for performing an uncontrolled exit. With that, maybe also damage players entering the room via means other than the miniaturizer. (After creating a compact machine, I usually setup some alternate transport to the interior in order to avoid having to farm the fluid. I realize this goes against the mod's concept.)

It seems to me that having specific transport tubing between cube interiors adds unnecessary complexity. Leave the cube normally, transit to the other cube, enter the other cube normally. Any transport between cubes can be handled by whatever transport is otherwise available.

**Comment by Thunder-Nova** [comment]
@ouroborus 
In CM2 (cm2-2.0.0-b104) there isn't, I can usually teleport players in, but it did help me show my friend how to do certain compact-able builds.

As for player protection, in the CM1 usually was fixated on the teleport, no one can teleport in the cube. They would teleport in their main cube with the added effect of Wither and Nausea. (not out)

idk about CM3. Since the servers I played up till now used CM1 and 2.

I would love to see a form of direct connection between the compact cubes. Either by tube or direct placement between the cubes. When I played with CM2 kinda bothered me a bit that the device really drains when travelling between multiple cubes. 

So a GUI could be useful. Mainly the user can control the connection and teleportation for the cubes. Which in returns satisfy both a form of protection, and a form of sharing. And tp protection towards the outside (overworld) of the cube or spawn depending on the GUI. The spawn (recently though of it) would be useful against mods that forces a teleportation of player to player, or player to location. (I seen a few mods that have those)
