### ISSUE TITLE
Is there any 1.12 mod that works with CM?

### ISSUE THREAD

**Issue by scottwilson0308** [CompactMods/CompactMachines#231]
So far, I've tried RFTools, Mekanism, ExtraUtilities2 and Vanilla connections.. EU2 Transfer pipe doesn't seem to work, RFTools Energy Cell doesn't seem to work, Mekanism Universal Cable doesn't seem to work and even Vanilla hoppers won't push items into a chest placed inside the CM.. has anyone found a way to transfer items or energy into/out of a CM in 1.12.1? I've got tunnels placed on all 4 cardinal sides of the CM with hoppers into 2 sides of the CM in the overworld ATM, unable to transfer..

**Comment by davenonymous** [comment]
Weird. Vanilla Hoppers into Chests definitely works. Transferring RF into machines etc works fine as well.

Not sure what you are doing wrong - are you aware that the tunnels are connecting to a specific side of the machine and you can cycle those by right clicking? If you can't decipher the textures (I've got to do something about that), Waila/TheOneProbe shows which one.

As transfer without a buffer inbetween I currently recommend using Thermal Dynamics.

**Comment by scottwilson0308** [comment]
I have RPG HUD and Xaero's Minimap both showing me compass direction, placing tunnels inside the machine on all 4 sides with chests in front, with two hoppers outside on the north and east sides with neither pushing into the chests.. I'm placing my tunnels on each side without clicking again, and each is different which (I admittedly assume) should be defaulting to the side it's placed on.. I've also had energy cells from RFTools both inside and out with one out to the machine, and the other in from the tunnel.. proper direction again. Wondering if one of my mods might be causing an issue.. I have Optifine 1.12.1 HD U C5, VanillaAutomation, Redstone++, Random Tweaks, Tiny Progressions and many others which I doubt could cause any issues.. I'll continue to fiddle around and figure out what the problem is.. I'll let you know if I discover anything.

**Comment by davenonymous** [comment]
They are not defaulting to the sides they are placed on, but placing them against a wall is easiest to decipher if you don't have Waila.

This is quite hard to read here due to contrast and blurring, but it might help:
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_north.png?raw=true" width="32" height="32" /> North
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_east.png?raw=true" width="32" height="32" /> East
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_south.png?raw=true" width="32" height="32" /> South
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_west.png?raw=true" width="32" height="32" /> West
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_up.png?raw=true" width="32" height="32" /> Up
<img src="https://github.com/thraaawn/CompactMachines/blob/1.12.1/src/main/resources/assets/compactmachines3/textures/blocks/tunnel_down.png?raw=true" width="32" height="32" /> Down

**Comment by scottwilson0308** [comment]
Right before reading this I tried f3 on the tunnel and noticed what you stated.. hopper now works properly which will help to a degree. Will try Thermal Dynamics for energy transfer, just wondering if there's any hope for multiblock item/fluid pipes or energy transfer cables in the future.. is that even possible with 1.12 and Forge's current capabilities?

**Comment by scottwilson0308** [comment]
Okay. Sorted out the tunnel problem, now I managed to actually get RF to transfer from inside the machine to the outside using Mekanism cable. Half way there. Unfortunately, when I swap the generator and device to be powered, the RF won't transfer into the machine.. Will try Thermal Dynamics.

**Comment by scottwilson0308** [comment]
Can I just delete this whole issue? I don't want evidence of it. Problem was simply assuming tunnels had a default config to the side they're placed on. EU2 Flat Transfer Nodes work perfectly fine with the machine, so I don't even care about the pipes. I'll figure something out for transferring energy into the machine, no big deal. Sorry for your wasted time reading this bogus issue!

**Comment by scottwilson0308** [comment]
Well thank you for all of your hard work! One final question is whether or not it's possible to transfer items and energy directly from one machine to the next via the overworld, or if nesting is the only way..

**Comment by davenonymous** [comment]
No worries! Always happy to answer questions and help with usability problems.
This issue shows that I have to update the textures for the tunnel, so you did good :)

If the compact machines are placed right next to each other you can just tunnel from one directly to the other.

**Comment by scottwilson0308** [comment]
Agreed.. Should be easier to update the textures with a simple N, S, E, W, U, D than to have it default to that side.. less confusing! I tried yesterday to put two CM right beside each other and have them work together but failed.. knowing my troubles that I've had with tunnels, I'll try again today.. if you say it works, I'll just have to double-check!
