### ISSUE TITLE
[1.12] Item scaffold for Projector custom recipes

### ISSUE THREAD

**Issue by jesmores** [CompactMods/CompactMachines#262]
Projector recipes seem limited right now to placeable blocks in the world. It would be nice to be able to use items in the recipes too. Maybe a simple "scaffold" like block that can be placed in the world and can hold a single item inside so it can be used in a Projector recipe?

**Comment by davenonymous** [comment]
I've thought about this before, but it's not as easy as it might sound, because I would have to render that scaffolding block with a TESR to show the item its holding or do some trickery when rendering it during crafting and in JEI.

At the moment, with the current rendering system this probably won't happen. And other mods adding pedestal type blocks will not render properly either 😭 
I have some ideas how this could be circumvented, but the best way really would be to allow TESRs to be rendered.

For now I'll leave this issue open as it's something that would neatly open up a whole new set of possible recipes.

**Comment by jesmores** [comment]
Ah I'm guessing the TESR issue is also why when I made a recipe that had pipes in it, the pipes didn't render in the JEI panel or in the crafting animation too :)

As an intermediate stage, what if the block was a generic container (like a one-slot chest) that was opaque and didn't render the item inside it? It would allow the recipes to be made and table the rendering problem for later? Although, that would make it pretty hard to figure out where the items should go in the JEI preview ...

In any case, glad you're thinking about it, and hope you can figure it out :)
