### ISSUE TITLE
[1.12] Lag while inside Dim 114

### ISSUE THREAD

**Issue by Orticus** [CompactMods/CompactMachines#270]
ATM 3 Modpack

When a player enters a compact machine the server starts spamming errors. The player inside the machine as terrible block lag and so do players in the overworld. Once player leaves the DIM server returns to normal and the block is performing normally (small test farm).

`6:30:06 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2018ms behind, skipping 40 tick(s)
6:30:29 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 9061ms behind, skipping 181 tick(s)
6:30:43 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6169ms behind, skipping 123 tick(s)
6:31:01 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6509ms behind, skipping 130 tick(s)
6:31:23 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 9360ms behind, skipping 187 tick(s)
6:31:36 PM CONSOLE: thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6092ms behind, skipping 121 tick(s)`

 I'm a newer server admin so just let me know what you need from me and Ill do my best to help.

**Comment by davenonymous** [comment]
Simply being in the CM3 dimension does not cause this mod to do anything computationally intensive (it checks the players position once every second). It should not cause the problems you are seeing. I assume some other mods blocks you've placed inside the machine to be causing this.

I need more information on how this can be reproduced:
- Which version of the mod are you playing with?
- Does it matter which machine someone goes into and does it matter whats inside? What happens when you enter an empty machine? Which blocks need to be inside for it to get laggy?
- Did I understand correctly that the inside of the machine is working just fine until someone enters it?

**Comment by Orticus** [comment]
- Version 3.0.03-b169
- Only one machine has been made so far, which is a max size, the block lag and server console spam started when it was empty.
- Auto smelting and farm are inside now, it continues to work (can pump in items and output power) but server spam and lag only happens when I'm inside.

**Comment by davenonymous** [comment]
I don't think your issue is related to Compact Machines in particular, but rather a "player is changing dimension" issue. Compact Machines on their own do basically nothing, they alone can not possibly be the reason why your server is lagging behind that much.
Seems more like a worldgen issue to me. Edit: The compact machine dimension is a void dimension, not much generation going on there.

**Comment by robotgryphon** [comment]
Will need to verify with the latest build for CM3 (278) and determine if this is still an issue.
