### ISSUE TITLE
1.12.2 OpenComputers support doesn't seem to work

### ISSUE THREAD

**Issue by Cruor** [CompactMods/CompactMachines#279]
Cannot seem to get OpenComputers too connect through the machines. @Vexatos has confirmed this has been a feature in the past. 

Pictures of the setup I attempted. I haven't used this mod since around 1.7, so excuse me if this is my fault.

![Inside](https://cdn.discordapp.com/attachments/191924371856687104/391723738443415553/unknown.png)
![Outside](https://cdn.discordapp.com/attachments/191924371856687104/391723731703037952/unknown.png)

Version: 1.12.2-3.0.3-b169.jar

**Comment by Vexatos** [comment]
>This means that TileEntities using capabilities to talk to each other will work out of the box

As a note, Environments are actually capabilities since Minecraft 1.11.2.

**Comment by Cruor** [comment]
Seems that the problem was only visual after more testing thanks to @Vexatos

**Comment by Vexatos** [comment]
Since it seems to be client-side only (cables not visually connecting), you might want to look into how much adding just a dummy environment via CapabilityNullHandler would break OpenComputers. With any luck it might just work. As I mentioned, I am pretty sure that Environment has only been a capability since Minecraft 1.11.2, so you will not get it working that way in 1.10.2.

**Comment by davenonymous** [comment]
I'll test an "EnvironmentNullHandler", but since these are only used on the clientside I don't expect any problems.
Edit: It appears the OpenComputers capabilities are not part of its API at the moment.

**Comment by Vexatos** [comment]
The environment capability is a `Capability<li.cil.oc.api.network.Environment>`. Instead of implementing Environment, you can now simply attach that capability, although implementing it still works (OC then attaches the capability automatically). Just `@CapabilityInject` that and it should work just fine. I am also pretty sure that that one is the only one you need, along with maybe `SidedEnvironment` although I am not sure if you can implement a dummy for that - maybe it works without.
