### ISSUE TITLE
Direwolf20 1.12.2 v1.2.0 Can't connect AE network through Compact Machine

### ISSUE THREAD

**Issue by taise007** [CompactMods/CompactMachines#292]
I'm unable to get either the port or redstone port to allow connecting AE networks into a compact machine.  The port recognizes there is an AE cable on the other side, but won't connect.

Is this a compatibility issue or am I missing something?

**Comment by davenonymous** [comment]
Both. Yes it's a compatibility issue and yes you've missed reading [this](https://github.com/thraaawn/CompactMachines#compatibility).
That section mentions another mod that helps with AE2 connections. Enjoy!

**Comment by mcdodge34** [comment]
Right to the point I needed the link you provide gave me the mod I needed to connect my AE2 network, was nicely designing a big and ugly compact machine full of drawers and a drawer controller to hook it to my AE2 network when I realized cables didn't connect, maybe you should update the curseforge page with a link to this since I had to search the github to find it.
