### ISSUE TITLE
16 by 16 vs. 13 by 13

### ISSUE THREAD

**Issue by CTH999** [CompactMods/CompactMachines#306]
Suggestion- 1 Chunk. I think the internal area of the final tier compact machine should be 16-16-16 instead of 13-13-13. By doing this, you can fit a _Tier 8_ draconic orb inside.

However, It's just a suggestion. It's your choice seeing as it's your mod. (Last time I checked at least)

**Comment by davenonymous** [comment]
Due to the way some of the mechanics work this is not possible without a major rewrite.
It would also break existing 13x13x13 machines.
--> Not going to happen, sorry.

**Comment by CTH999** [comment]
Ok, makes sense!

I completely understand!

(And since It's for the Draconic Orb, maybe It's better you can't put it in a block and pull around 2^64 rf with you!)

**Comment by Saklad5** [comment]
What about in Compact Machines 4? I suppose anything above a 14x14x14 would span multiple chunks because of the walls, though…

**Comment by Saklad5** [comment]
@CTH999 The Tier 7 Draconic Orb, which is the most practical in my opinion, _just_ fits inside a Maximum Compact Machine. Because it is a sphere, it actually leaves plenty of space for input, output, and movement.

**Comment by CTH999** [comment]
@Saklad5 Yup, I knew that, I already did some math on the anything above 14x14, and...

You're right, the tier 7 works. Just not the tier 8. And, since the tier 8 is so OP, it's probally better that way!

**Comment by Saklad5** [comment]
@CTH999 Actually, I think Tier 8 isn’t that overpowered. Tier 7 is already very difficult to fill, and Tier 8 is expensive in a way that cannot currently be automated as far as I know.

**Comment by CTH999** [comment]
It can be automated, it's just how much power it stores, so maybe It's better that It can't fit in!

**Comment by CTH999** [comment]
Come to think of it, when you update to 1.13, would this be a nice change?

**Comment by Saklad5** [comment]
That’s what I meant when I said Compact Machines 4. They increment the number with every Minecraft version, I understand.

And no, it cannot be automated unless you can devise a way of automatically spawning and killing Ender Dragons. Since they break all blocks near them, that’s virtually impossible.

You can make an RFTools dimension full of Ender Dragons and use a Draconic Bow to get enough, but that’s not automation. If you had a block-protecting mechanic that worked against Ender Dragons, you might be able to rig something using a Draconic Bow and right-clicking machine spraying arrows at 0,0.
