### ISSUE TITLE
Single player: 'disconnected' when lookin in Giant (empty hand)

### ISSUE THREAD

**Issue by dm8mydog** [CompactMods/CompactMachines#311]
**Compact Machines version**: 3-1.12.2-3.0.7-b197
**Forge version**:  14.23.2.2618
**I am not using Optifine**: indeed not

[Netty Local Client IO #1/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.IllegalStateException: Grid features for me.yrf.mcmods.capadapter.ae2.TileAECapAdapter$AEGridProxy@5ba15460 are server side only.

Note: I have a Giant Compact machine on top of a capabilties adapter on top of a regular AE2 glass cable (in case it matters)

When in single player, right clicking with an empty hand the Giant Compact machine 'disconnects' the player from the (local) server process. The game does not crash *the first time* and world can be re-entered without much fuss. If you *repeat* the act... ie. so you can copy the log error and paste it here *sigh* ...then the game will crash :/

The Maximum compact machine does not have this issue btw.

**Steps to reproduce:** Right click w/ empty hand on a Giant compact machine in a Single player world.

Love the mod, cheers :)

**Comment by davenonymous** [comment]
You've skipped this step: Please read [this](https://vazkii.us/br101/) and follow there instructions in there before creating an issue.

Please don't skip steps. It says where you can find the crash log and where you can upload it.
Screenshots (from the in and outside) also help so I might be able to reproduce the issue.

I need more information, because all you are saying is: right clicking a giant compact machine crashes the game. How did you reproduce this issue in a test world?

**Comment by andr9528** [comment]
This disconnect error is still present while using these version, i believe it is a crossmod issue between this mods rendering of the room, and 'ME Capability Adapter's adapter block.

appliedenergistics2-rv5-stable-11
capabilityadapter-1.0
compactmachines3-1.12.2-b200
forge-14-23-3-2676
minecraft 1.12.2

Underneath is a paste with the hole error from the log file, as no crash file is generated by this error.
https://pastebin.com/bJqasCE9

Will try to reproduce the error in a testworld tomorrow, and upload images of setup

**Comment by robotgryphon** [comment]
Needs verified on b278 and the latest versions of the affected mods.
