### ISSUE TITLE
Crafting Performance Issue

### ISSUE THREAD

**Issue by Sir-Will** [CompactMods/CompactMachines#317]
Any chance this can be improved? This seems a lot for crafting.
![](https://i.imgur.com/tyHZ2hU.jpg)
compactmachines3-1.12.2-3.0.7-b197

**Comment by davenonymous** [comment]
I will look into this in a future version. Currently I only have the time for a small round of bugfixes. Sorry, very busy at the moment.

**Comment by robotgryphon** [comment]
This is being addressed in Compact Crafting for 1.16+. Due to 1.12's age, a major refactor in CM3 probably will not happen, but Compact Crafting will solve this by only doing recipe scans when blocks near the crafting fields change by a player. For automation, I plan to add a redstone-controlled block that will kick off the recipe scan/start/stop process.
