### ISSUE TITLE
GTCE compat

### ISSUE THREAD

**Issue by Agrax** [CompactMods/CompactMachines#342]
Would it be possible to add a GTCE cables compatibility? For now the only option would be an RF channel (FE support will be added soon), but it forces ppl to change EU->FE->EU. Ofc it's not THAT big of a deal, but if you were able to make it compatible that'd be great

**Comment by davenonymous** [comment]
There is no and will never be any custom compatibility implementations for other mods.

Please ask the mod authors to switch to a Forge Capability based system and it will automatically work out of the box.

Edit: A few more notes:
- I have no clue what GTCE even is.
- It makes no sense for me to add compatibility for **all the other** mods, when all the other mods could just make their mods compatible themselves **very** easily (it's not even CM specific, but a Forge thing!).
- I got burned out from the 1.7.10 version because of custom compatibility implementations and dropped compact machines development for almost 2 years. Only the advent of Forge Capabilities (which is what tunnels are based on) made me reconsider.

**Comment by Agrax** [comment]
GregTech: Community Edition... So if the mod im talking abt already USES forge caps it’ll just work fine on its own, w/o you even making a compat? Great to hear, thanks

**Comment by davenonymous** [comment]
Yupp, that's exactly right.
All sided(!) forge capabilities are supported out of the box!
You are welcome! Feel free to refer them other mod authors to me should any issues arise.
