### ISSUE TITLE
<forestry:arboretum> breaks walls from modification Compact Machines.

### ISSUE THREAD

**Issue by prokopiy** [CompactMods/CompactMachines#350]
<forestry:arboretum> breaks walls from modification Compact Machines.

forestry_1.12.2-5.8.1.325.jar

**Comment by DemonFiend** [comment]
Im Also noticing this issue, came here to report it and saw this aswell xD, it breaks the blocks because the Max size is 1 block too big from center, would need some sort of if statement to detect if a forestry farmer is placed or somehow make it unable to be destroyed by the machines.

**Comment by davenonymous** [comment]
[The walls have setBlockUnbreakable() set](https://github.com/thraaawn/CompactMachines/blob/018a6a291070666303001d5d4547c8a97895cc15/src/main/java/org/dave/compactmachines3/block/BlockProtected.java#L19) and a few other checks to prevent players from being able to remove the walls.

Forestry is replacing blocks though, which is not being blocked. Will be fixed in the next version.
