### ISSUE TITLE
Problem with jams 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [CompactMods/CompactMachines#352]
**Compact Machines version**:Compactmachines3_1.12.2_3.0.12-b220
**Forge version**:forge-1.12.2-14.23.4.2705-universal
**I am not using Optifine**:
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Description of the problem including expected versus actual behavior:**

I started using the Extreme Reactors.
I built a lot of block structure, launched it, everything is fine. In addition, that when I returned again to CM, I was stuck right in the reactor)

Screenshots attached.

Can I make sure that I do not get stuck inside the blocks?

https://i.gyazo.com/a39b3a1b2f9178bed0285f2d58e26b5b.jpg
https://i.gyazo.com/2d1f837b2df9aaf6876d94f284d8fca5.jpg
https://i.gyazo.com/160fcc405e601b8e0f4b3b274d5fa870.jpg
https://i.gyazo.com/561ae9ebab5d7301b38f4a4ece41480f.jpg
https://i.gyazo.com/64afd3c3887b17a84ff049749f9f2a26.jpg

**Comment by davenonymous** [comment]
What happened to "Also make sure you've read the full readme"?

**Comment by xxxLEOPARDxxx** [comment]
I apologize ...
I read the manual, figured out how it works :)
Thank you very much!

**Comment by davenonymous** [comment]
No worries. The idea with that sentence in the issue template is to save both you and me some time.
You would have had the solution after about ~5min of reading instead of having to wait for 9 hrs to be told to just read the manual.

It is most of the times much more efficient to search for a solution yourself for a bit instead of asking for help right away. Makes you a happier person to because you a solving your own problems.
