### ISSUE TITLE
Restrict ticking of tileentities to the cube?

### ISSUE THREAD

**Issue by Bucky420** [CompactMods/CompactMachines#358]
some how people are able to get out of the cube if u can fix this that would be better but if not just disable ticking of things out of it :)

**Comment by davenonymous** [comment]
No, just no.

I really need a bot to auto-close these kind of issues:
1) Don't just ignore everything the template says OR accept that the dev ignores everything that's in your issue report.
2) You are already being teleported back inside automatically. Since you didn't specify anything, i assume you are running a version that does not have this feature included. Please update to the latest version.
