### ISSUE TITLE
ME conduit compatibility

### ISSUE THREAD

**Issue by ghost** [CompactMods/CompactMachines#373]
**Compact Machines version**: 1.12.2-3.0.13-b326
**Forge version**: 2800
**I am not using Optifine**: Optifine breaks everything, nope
**Link to Crashlog**: n/a

Preface: I know about the capability adapter, however this applies to the ME conduits within ender io (a different item) and that mod doesn't have a proven track record of updating, so I can't use it. I also know about quantum tunnels, however having that giant thing in my base rather defeats the point.

I would like to request compatibility be added for ME conduits and dense ME conduits so that they can connect through tunnels without additional blocks.

**Comment by davenonymous** [comment]
Sorry, no. I won't add custom mod compatibility. It's the mods job to do that.
Request them to support world-aware, sided forge capabilities so compact machines (and other mods like capability proxy) are automatically compatible to them.

**Comment by ghost** [comment]
Ah alright, I wasn't sure which side needed to add it. I will go make a report over there.

**Comment by ghost** [comment]
I went up the chain (as you can see) and was essentially told that it is up to you to implement the ae2 grid for this to work as compatibilities just won't work well for ae2. I was also told that you intentionally do not support anything other than capabilities. Why I do not know, but as this kind of behavior goes against what I want to see in mod devs, I have elected to remove the mod from my pack.

**Comment by davenonymous** [comment]
I indeed do not support other methods, because it is way to much work to keep up with all the mods that I would need to support - i had enough experience with that in cm1 that i nearly fully dropped supporting the mod at all.

Forge Capabilities is the API I'm using. It's an official forge api that is encouraged to be used by mod authors for mod interaction. I'm not sure why you think I need to provide another way or add custom integrations that are not using that system myself.
I fully understand the reasoning behind the AE devs decision (hey guys) not to use capabilities, but in the end that means it won't work with compact machines (or other mods proxying capabilities) directly. And that's fine. Especially because there is a fix with ruifungs capability adapter.

Since you are a bit entitled regarding what mod devs have to do for you, I'm perfectly fine that you are removing the mod from your pack.

**Comment by ghost** [comment]
Sad, I had planned out my entire AE2 system into a set of Compact Machines (Crafting Processors, Storage, ME Controller, TD machines) and started building the machines, only to discover that while they show the cables inside and out they cannot connect unlike most other mods.

Are you sure you can't work with the other mod guys to make something happen?

**Comment by davenonymous** [comment]
It has nothing to with "not being able to work with other mod guys" or not having the technical know how. It was a feature in CM1 after all... It was a deliberate decision not to open these floodgates again. A design decision to go the way of least resistance and make as much as possible compatible out of the box.

This crying on the highest of levels is really annoying and unnecessary. There already is a way to solve this issue by placing a single block on the in- and outside of the tunnels. Does the capability adapter block not work for you or do you just don't know about it, @Sorbe?
