### ISSUE TITLE
compact and mek

### ISSUE THREAD

**Issue by JohnsBack** [CompactMods/CompactMachines#402]
**Compact Machines version**:newest
**Forge version**:newest
**I am not using Optifine**:yes HD U E3
**Link to Crashlog**:(https://github.com/thraaawn/CompactMachines/files/3258787/crash-2019-06-05_15.21.28-server.txt)

**Description of the problem including expected versus actual behavior:**
I start the server and it crashes a sec or two later

**Steps to reproduce:**
lol start my server

I talked to the Mek people and they said you might be able to tell me whats going better.

**Comment by Frikkle** [comment]
This issue happens when placing certain blocks against certain tunnels. I fixed a similar issue for Redstone tunnels (see https://github.com/thraaawn/CompactMachines/pull/391). You could solve this issue in a similar way. Perhaps it would be best to go through the whole codebase and add null-checks where applicable.

To solve the issue easiest you can set the "removeErroringTileEntities" flag to true and start your server. It will remove the conflicting entity. That should at least start it up again.
