### ISSUE TITLE
Issue creating custom miniaturization recipes.

### ISSUE THREAD

**Issue by wormzjl** [CompactMods/CompactMachines#414]
compactmachines3-1.12.2-3.0.18-b278

I have the following script which I've used for testing.
https://gist.github.com/wormzjl/3be408cca63d621d5c1b15bb70f95d5e
It shows correctly in preview
![image](https://user-images.githubusercontent.com/2989009/65920350-11f51f80-e3df-11e9-89c2-203d0b80f6b1.png)
However when placed in world it's not recognized by the projector.
Does the miniaturization work with block with orientation such as stairs?

**Comment by SashaGelert** [comment]
This was easy.  In your 3x3 recipe for the field, an air block is represented by an underscore "_", whereas your script uses a hyphen "-". This looks the same in the preview because it's trying to render a "null" or void block in the corners, which looks empty, but when it triggers the field it checks for a "null" which doesn't exist as a block state, and thus the recipe fails.

**Comment by landpointpro** [comment]
i having the same issue but i wanna make a bigger compact machine size instead of a13x13x13

**Comment by SizableShrimp** [comment]
Making a bigger machine size past 13x13x13 will never be possible, as those dimensions would extend past one chunk and would break a lot of the mod.

**Comment by robotgryphon** [comment]
Closing, this is resolved.
