### ISSUE TITLE
Compact Machines Chunk loads not as expected

### ISSUE THREAD

**Issue by idnthvn** [CompactMods/CompactMachines#419]
**Read then remove this section**:
Do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/CompactMachines/blob/1.12.1/README.md) on github.

If you are reporting a bug regarding the interior view of the Machines, the one you get when you right click a machine, do not report it to any other mod author involved in the crash. It is highly likely that its CM3s fault.

**Compact Machines version**: 1.12.2 3.0.18 -b278
**Forge version**: 1.12.2 2847
**I am not using Optifine**: yes i am
**Link to Crashlog**: N/A
**Screenshot (if possible)**: N/A
Using SpongeForge as well Version 7.1.10RC4000

**Description of the problem including expected versus actual behavior:**
Issue: Chunk is Loaded in overworld
Expected: Chunk is overworld is not loaded

Player who owns the machine is OFFLINE. Therefore should have zero chunks loaded. 
Config has it set that CM is only loaded when the chunk the CM is in, is loaded.
I have limited this to the TUNNELS being the issue
**Steps to reproduce:**
Install mods, forge, etc.
Make sure Chicken Chunks mod is installed.
Enter server and place a CM machine. Leave area and use /chunkloaders command to see chunks loaded. CM machine is not loaded and chunk in overworld is not loaded.
Go back to CM and enter inside, Place a tunnel on anywall. (test was on the floor). In the chunkloader view, you will see that the chunks went away as you entered the machine, and after you place the tunnel, 1 chunk is now loaded (the chunk the CM is in)

Please fix this.

.

**Comment by daiaji** [comment]
I ran into a situation similar to yours. When I left dimension 144, it seemed that only the part of the block where the pipeline was laid was loaded, and chickenchunks didn't seem to have any effect. Then I tried IC2's chunk loader, and the result was the same.

**Comment by robotgryphon** [comment]
Need to verify this one against SpongeForge and the chunk loading mods; I believe we have another issue with chunkloading relating to that. Thanks for the report.

**Comment by SizableShrimp** [comment]
A CM room does not generate until you enter it for the first time. These steps don't seem to hold up. I might agree that this is a tunnel issue based on the fact that once you first load the CM room with a tunnel, it loads and checks the block outside of the machine where the tunnel is set. This means it must load the chunk to do that. Then, since the chunk it just checked for a block to connect through the tunnel is the same chunk with the machine block, it loads itself. This is all assuming that the config option for chunkloading the CM room if it is loaded is enabled. This might be the cause, but this might also not be possible.
