### ISSUE TITLE
About Crafting bug

### ISSUE THREAD

**Issue by UnaRem** [CompactMods/CompactMachines#435]
mod version:compactmachines3-1.12.2-3.0.17-b267
Using the Extra Utilities 2 Mechianical User and the Not Enough Wands, Acceleration Wand, accelerates the Block in the Crafting area center, dropping more products.

**Comment by UnaRem** [comment]
and Extra Utilities 2 Interactionproxy

**Comment by robotgryphon** [comment]
I wouldn't call this one a bug; more of an unintentional feature due to how the crafting process and preview work. (Haha, "not a bug it's a feature" here).

That said, this one is probably going to be difficult to fix due to the number of tick-accelerating mods in 1.12, and the knowledge of the ticking block in the center of the crafting field.

Relevant code block for item dropping: https://github.com/CompactMods/CompactMachines/blob/1.12.1/src/main/java/org/dave/compactmachines3/tile/TileEntityCraftingHologram.java#L61-L73

**Comment by SizableShrimp** [comment]
I feel like this issue is a `wont-fix` scenario. It shouldn't be OUR fault that crafting is being sped up by another mod. Either disable the feature in the mod or don't/do use it.

**Comment by UnaRem** [comment]
As a feature, maybe it can be a shortcut to play.

**Comment by SizableShrimp** [comment]
Not sure what you mean by this.

**Comment by robotgryphon** [comment]
The real issue here isn't the crafting speed (that's a whatever as far as I'm concerned -- balance, maybe, but not *broken*). The issue here is more outputs dropping than what's been specified.

However, I'm agreeing with Shrimp and my original point; given the complexity, this is probably not going to be fixed before end of life for CM3.

**Comment by SizableShrimp** [comment]
What mod is causing the duplication in output drops, @UnaRem?

**Comment by UnaRem** [comment]
Extra Utilities 2 and Not Enough Wands

**Comment by UnaRem** [comment]
This is certainly not a very common option, as the Acceleration Wand from my modpacks has been modified to do away with RF.

**Comment by SizableShrimp** [comment]
Which items in particular are you using to duplicate outputs from those two mods?

**Comment by UnaRem** [comment]
The first comment explains how to create this bug
