### ISSUE TITLE
Entering Compact Machine dimensions causes xp bar to be reset, but only visually

### ISSUE THREAD

**Issue by NielsPilgaard** [CompactMods/CompactMachines#482]
**Description of the problem including expected versus actual behavior:**
After using the Personal Shrinking Device to enter a Compact Machine, the player's xp bar is set to 0. Gaining or losing xp after that causes the xp bar to refresh, so it's only a visual bug.

Expected behavior: For xp to remain the same when travelling between dimensions

### Mod and Forge Versions
> Do not use "latest" for versions. Be exact; it helps us track down the issue more accurately.

**Mod Version:** 4.0.0 beta 2
**Forge version:** 1.16.5 - 36.2.2

### Crash Information
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)

**Steps to reproduce:**
1. Gain xp
2. Enter Compact Machine
3. Observe bug

**Comment by embeddedt** [comment]
As far as I know, this is or at least relates to a vanilla bug that's existed in various forms since at least 1.12, and is caused by player capabilities and/or attributes not being copied over properly when the player changes dimensions.

[This mod](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug) works around the issue by forcefully resending the experience amount after a dimension change.

**Comment by NielsPilgaard** [comment]
It is indeed, I'll install that mod then, ty 👍
