### ISSUE TITLE
Pipes not connecting to compact machine

### ISSUE THREAD

**Issue by xWires** [CompactMods/CompactMachines#571]
### I am not using performance mods.

- [X] Confirm

### Description

Pipes are not connecting to the outside of a compact machine, I have tried the pipes from Pipez and also the pipes from Mekanism, neither of them work.

(I'm playing on FTB StoneBlock 3 by the way)

### Mod Version

4.5.0

### Forge Version

1.18.2 - 40.2.1

### Screenshot (if available)

![2023-08-03_00 45 57](https://github.com/CompactMods/CompactMachines/assets/68852080/040f572a-3073-4e3a-b187-fa48f7b8bf83)
![2023-08-03_00 45 59](https://github.com/CompactMods/CompactMachines/assets/68852080/d5198910-8a84-4027-917c-60dedd3663a8)
![2023-08-03_00 46 45](https://github.com/CompactMods/CompactMachines/assets/68852080/d4df4b80-3a87-4e17-a08a-963284ac5288)

### How to reproduce

1. Place a compact machine
2. Place a tunnel inside the compact machine
3. Try to connect a pipe to the outside

**Comment by nornagon** [comment]
I'm also seeing this issue with Compact Machines 5.1.0 on 1.19.2.

**Comment by Jake-san2** [comment]
I was struggling with this issue, until I read the other issues posted that were similar. My connection issues in Seapolis 2 that has 5.1.0 were merely chunk loading issues. I went to the FTB Utilities map (M key) and claimed / chunkloaded the compact machines chunk. Now the power tunnel transfers power in real time. I didnt realize first that the order of connection of Pipez mod pipes and the Tunnels out matter, since if the compact machine dimension is not chunkloaded, there is only chunk loading existing I made my self when jumping in and out.
Edit: Also, the order of tunnels and pipes is very particular. First tunnels are placed inside, then pipes to them. Only then the connections outside. If for eg. pipes were connected outside before, reconnecting them does not fix the issue.

**Comment by nornagon** [comment]
I tried force-loading the room chunk two different ways: first, by using the chunkloading upgrade on the block, and second using FTB Chunks. Neither changed the behavior; Pipez pipes still don't connect to the tunnel. I also did place the tunnel inside before placing any of the connections outside the block, and tried mining and re-placing the machine block, which also didn't make a difference.

**Comment by Jake-san2** [comment]
> I tried force-loading the room chunk two different ways: first, by using the chunkloading upgrade on the block, and second using FTB Chunks. Neither changed the behavior; Pipez pipes still don't connect to the tunnel. I also did place the tunnel inside before placing any of the connections outside the block, and tried mining and re-placing the machine block, which also didn't make a difference.

Did you have something going out the tunnel first before attaching the pipez? The Seapolis 2 modpack doesn't have recipe for the chunkloader for the mod enabled, but I doesn't seem to be working. Disabling FTB Chunks chunkloading and applying the upgrade doesn't transfer more power ou, only the amount that was on the tunnel coming out. As soon as I enable FTB Chunks chunkloading, power starts to move out.

**Comment by nornagon** [comment]
Yep, I have some lava waiting to come out the tunnel

**Comment by nornagon** [comment]
I tried this on the latest 5.2.0 build (built from source) and couldn't reproduce there. So I guess the rewritten version is working :) looking forward to a 5.2.0 release.

**Comment by nornagon** [comment]
Hm, so I built 5.1.0 locally and couldn't reproduce it there, so I tried again in the world where the bug was happening, and with a fresh machine and tunnel everything connected properly. Then I broke the CM block and moved it, and after that, pipes wouldn't connect again.

Then I tried that in my local 5.1.0 build and it reproduced there, too.

Steps:
1. `/give @s compactmachines:machine_normal`
2. Place the machine
3. Enter the machine
4. `/give @s compactmachines:tunnel{definition:{id:"compactmachines:fluid"}}`
5. Place the tunnel on a wall
6. Exit the machine
7. Place a fluid pipe on the top face of the machine block
8. The pipe will connect
9. Break the machine block and place it again somewhere else
10. Place a fluid pipe on the top face of the machine block
11. The pipe will not connect

I think this is because when the CM block is re-placed, the tunnel connection graph isn't correctly updated to account for the moved block. Removing and re-placing the tunnel inside the machine (shift-rclick with an empty hand to remove a tunnel) refreshes the tunnel connection graph, and after that placing pipes works again in the new position.
